name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (minimal)
        run: |
          python -m pip install -U pip
          python -m pip install -r proofcite/requirements.txt
      - name: Run tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1
        run: |
          cd proofcite
          python -m pytest -q
